from pydantic import BaseModel


class DigiposRespConfig(BaseModel):
    DATA_EXCLUDE_SUBCATEGORY: list | None
    DATA_EXCLUDE_PRODUCTNAME: list | None
    DATA_EXCLUDE_QUOTA_METADATA: list | None
    HVCDATA_EXCLUDE_SUBCATEGORY: list | None
    HVCDATA_EXCLUDE_PRODUCTNAME: list | None
    HVCDATA_EXCLUDE_QUOTA_METADATA: list | None
    VOICE_SMS_EXCLUDE_SUBCATEGORY: list | None
    VOICE_SMS_EXCLUDE_PRODUCTNAME: list | None
    VOICE_SMS_EXCLUDE_QUOTA_METADATA: list | None

    DIGITAL_OTHER_EXCLUDE_SUBCATEGORY: list | None
    DIGITAL_OTHER_EXCLUDE_PRODUCTNAME: list | None
    DIGITAL_OTHER_EXCLUDE_QUOTA_METADATA: list | None

    DIGITAL_MUSIC_EXCLUDE_SUBCATEGORY: list | None
    DIGITAL_MUSIC_EXCLUDE_PRODUCTNAME: list | None
    DIGITAL_MUSIC_EXCLUDE_QUOTA_METADATA: list | None

    DIGITAL_GAME_EXCLUDE_SUBCATEGORY: list | None
    DIGITAL_GAME_EXCLUDE_PRODUCTNAME: list | None
    DIGITAL_GAME_EXCLUDE_QUOTA_METADATA: list | None

    ROAMING_EXCLUDE_SUBCATEGORY: list | None
    ROAMING_EXCLUDE_PRODUCTNAME: list | None
    ROAMING_EXCLUDE_QUOTA_METADATA: list | None

    VF_EXCLUDE_SUBCATEGORY: list | None
    VF_EXCLUDE_PRODUCTNAME: list | None
    VF_EXCLUDE_QUOTA_METADATA: list | None

    BYU_EXCLUDE_SUBCATEGORY: list | None
    BYU_EXCLUDE_PRODUCTNAME: list | None
    BYU_EXCLUDE_QUOTA_METADATA: list | None

    HVC_VOICE_SMS_EXCLUDE_SUBCATEGORY: list | None
    HVC_VOICE_SMS_EXCLUDE_PRODUCTNAME: list | None
    HVC_VOICE_SMS_EXCLUDE_QUOTA_METADATA: list | None
